spring:
  main:
    show-banner: false

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update

  datasource:
    url: jdbc:h2:./db/demo;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  thymeleaf:
    cache: false

